.TH "LightPad" "1" "" "Version 0.0.12 (handheld)" "LightPad Manual Page Documentation"
.SH NAME
com.github.libredeb.lightpad \- lightweight, simple and powerful
application launcher
.SH SYNOPSIS
.PP
\f[B]com.github.libredeb.lightpad\f[R] [ OPTION ] \&...
.SH DESCRIPTION
LightPad is a lightweight, simple and powerful application launcher.
It is also Wayland compatible.
.SH Options
.TP
\-h, \[en]-help
Show help options.
.TP
\-v, \[en]-version
Output the version number and exit.
.SH ENVIRONMENT VARIABLES
.TP
LightPad supports the following environment variables:
.PP
\-
\f[B]LIGHTPAD_CATEGORIES\f[R]: This variable controls which application categories
are displayed. Its value is a comma-separated list of category names (e.g., `Games,
System Tools, Internet`). The comparison is case-insensitive and ignores extra
spaces. If unspecified, all available categories are shown. Unrecognized category
names are silently ignored. Category names must conform to the freedesktop.org
menu specification.
.PP
\-
\f[B]LIGHTPAD_ONLOAD\f[R]: You can execute a script or command when LightPad starts
by setting the `LIGHTPAD_ONLOAD` environment variable. The command will be executed
before any part of the application is initialized.
.PP
\-
\f[B]LIGHTPAD_ONEXIT\f[R]: You can execute a script or command when LightPad exits
by setting the `LIGHTPAD_ONEXIT` environment variable. The command is executed after
closing internal components (like SDL) and just before the main application window
is destroyed.
.PP
\-
\f[B]LIGHTPAD_WAIT_SIGFILE\f[R]: If set, specifies a path to a signal or pid file.
LightPad will pause its shutdown sequence and wait for this file to exist before 
exiting completely. This is useful to allow background tasks started by
LIGHTPAD_ONEXIT to complete.
.SH FILES
.TP
\f[I]\[ti]/.lightpad/blocklist\f[R]
Hide applications using a blocklist file.
.SH AUTHOR
Juan Pablo Lozano \c
.MT libredeb@gmail.com
.ME \c