.TH "LightPad" "1" "" "Version 0.0.9" "LightPad Manual Page Documentation"
.SH NAME
com.github.libredeb.lightpad \- lightweight, simple and powerful
application launcher
.SH SYNOPSIS
.PP
\f[B]com.github.libredeb.lightpad\f[R] [ OPTION ] \&...
.SH DESCRIPTION
LightPad is a lightweight, simple and powerful application launcher.
It is also Wayland compatible.
.SH Options
.TP
\-h, \[en]-help
Show help options.
.TP
\[en]-display=DISPLAY
X display to use.
.TP
\[en]-help\-all
Show all help options
.SH FILES
.TP
\f[I]\[ti]/.lightpad/config\f[R]
Adjust visual aspects such as font size, icon size, and the application
grid layout.
.TP
\f[I]\[ti]/.lightpad/background.(jpg|png)\f[R]
Use a custom background of your choice.
.TP
\f[I]\[ti]/.lightpad/blocklist\f[R]
Hide applications using a blocklist file.
.SH AUTHOR
Juan Pablo Lozano \c
.MT libredeb@gmail.com
.ME \c
