.TH "LightPad" "1" "" "Version 0.1.0" "LightPad Manual Page Documentation"
.SH NAME
io.github.libredeb.lightpad \- lightweight, simple and powerful
application launcher
.SH SYNOPSIS
.PP
\f[B]io.github.libredeb.lightpad\f[R] [ OPTION ] \&...
.SH DESCRIPTION
LightPad is a lightweight, simple and powerful application launcher.
It is also Wayland compatible.
.SH Options
.TP
\-h, \[en]-help
Show help options.
.TP
\-v, \[en]-version
Output the version number and exit.
.TP
\-b, \[en]-background IMAGE_FILE_PATH
Allows you to pass the path of an image to use it as launcher background.
.TP
\-s, \[en]-save\-config
Get the default values of the configuration and stores them in \[ti]/.lightpad/config
.TP
\-c, \[en]-clear\-config
Clear the stored configuration, especially if you want to restore the default state.
.SH FILES
.TP
\f[I]\[ti]/.lightpad\f[R]
This folder contains all the configuration files and workspace of LightPad.
.TP
\f[I]\[ti]/.lightpad/cache\f[R]
This folder keep pre-rendered icons to improve the startup speed of Lightpad.
It is safe to delete it to clear the cache in case of any issues.
.TP
\f[I]\[ti]/.lightpad/config\f[R]
Adjust visual aspects such as font size, icon size, and the application
grid layout.
.TP
\f[I]\[ti]/.lightpad/background.(jpg|png)\f[R]
Use a custom background of your choice.
.TP
\f[I]\[ti]/.lightpad/blocklist\f[R]
Hide applications using a blocklist file.
.SH AUTHOR
Juan Pablo Lozano \c
.MT libredeb@gmail.com
.ME \c
